# Generated by Django 5.2.4 on 2025-11-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_remove_student_courses_assignmentsubmission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normative',
            name='mark',
        ),
    ]
