# Generated by Django 5.2.4 on 2025-11-26 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_remove_normative_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submission', to='education.teacher'),
            preserve_default=False,
        ),
    ]
