# Generated by Django 5.2.4 on 2025-12-01 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_student_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submission', to='education.teacher'),
        ),
    ]
