# Generated by Django 5.2.4 on 2025-12-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_student_birth_date_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
